/**
* Cactacea backend API
* Cactacea / Cactacea backend API for web and mobile applications
*
* OpenAPI spec version: 19.1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.github.cactacea.backend


/**
 * 
 * @param code code
 * @param message message
 */
data class CactaceaError (
    /* code */
    val code: kotlin.Long,
    /* message */
    val message: kotlin.String
) {

}

