/**
* Cactacea backend API
* Cactacea / Cactacea backend API for web and mobile applications
*
* OpenAPI spec version: 19.9.3
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.github.cactacea.backend

import io.github.cactacea.backend.User

/**
 * 
 * @param id 
 * @param replyId 
 * @param feedId 
 * @param message 
 * @param user 
 * @param likeCount 
 * @param warning 
 * @param rejected 
 * @param postedAt 
 * @param next 
 */
data class Comment (
    val id: java.math.BigDecimal,
    val feedId: java.math.BigDecimal,
    val message: kotlin.String,
    val user: User,
    val likeCount: kotlin.Long,
    val warning: kotlin.Boolean,
    val rejected: kotlin.Boolean,
    val postedAt: kotlin.Long,
    val next: kotlin.Long,
    val replyId: java.math.BigDecimal? = null
) {

}

