/**
* Cactacea backend API
* Cactacea / Cactacea backend API for web and mobile applications
*
* OpenAPI spec version: 19.9.3
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.github.cactacea.backend

import io.github.cactacea.backend.Medium
import io.github.cactacea.backend.User

/**
 * 
 * @param id 
 * @param message 
 * @param mediums 
 * @param tags 
 * @param user 
 * @param likeCount 
 * @param commentCount 
 * @param liked 
 * @param warning 
 * @param rejected 
 * @param postedAt 
 * @param next 
 */
data class Feed (
    val id: java.math.BigDecimal,
    val message: kotlin.String,
    val mediums: kotlin.Array<Medium>,
    val likeCount: kotlin.Long,
    val commentCount: kotlin.Long,
    val liked: kotlin.Boolean,
    val warning: kotlin.Boolean,
    val rejected: kotlin.Boolean,
    val postedAt: kotlin.Long,
    val next: kotlin.Long,
    val tags: kotlin.Array<kotlin.String>? = null,
    val user: User? = null
) {

}

