/**
* Cactacea backend API
* Cactacea / Cactacea backend API for web and mobile applications
*
* OpenAPI spec version: 19.3.4
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.github.cactacea.backend

import io.github.cactacea.backend.Account
import io.github.cactacea.backend.Medium

/**
 * 
 * @param id 
 * @param message 
 * @param mediums 
 * @param tags 
 * @param account 
 * @param likeCount 
 * @param commentCount 
 * @param contentWarning 
 * @param contentDeleted 
 * @param postedAt 
 * @param likedAt 
 * @param next 
 */
data class Feed (
    val id: java.math.BigDecimal,
    val message: kotlin.String,
    val likeCount: kotlin.Long,
    val commentCount: kotlin.Long,
    val contentWarning: kotlin.Boolean,
    val contentDeleted: kotlin.Boolean,
    val postedAt: kotlin.Long,
    val mediums: kotlin.Array<Medium>? = null,
    val tags: kotlin.Array<kotlin.String>? = null,
    val account: Account? = null,
    val likedAt: java.math.BigDecimal? = null,
    val next: java.math.BigDecimal? = null
) {

}

