/**
* Cactacea backend API
* Cactacea / Cactacea backend API for web and mobile applications
*
* OpenAPI spec version: 19.9.3
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.github.cactacea.backend

import io.github.cactacea.backend.User

/**
 * 
 * @param id 
 * @param user 
 * @param requestedAt 
 * @param next 
 */
data class FriendRequest (
    val id: java.math.BigDecimal,
    val user: User,
    val requestedAt: kotlin.Long,
    val next: kotlin.Long
) {

}

