/**
* Cactacea backend API
* Cactacea / Cactacea backend API for web and mobile applications
*
* OpenAPI spec version: 18.11.0-SNAPSHOT
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.github.cactacea.backend


/**
 * 
 * @param privacy_type Feed privacy type. By default the value is everyone.
 */
data class GetFeedsBody (
    /* Feed privacy type. By default the value is everyone. */
    val privacy_type: GetFeedsBody.PrivacyType? = null
) {

    /**
    * Feed privacy type. By default the value is everyone.
    * Values: everyone,followers,friends,self
    */
    enum class PrivacyType(val value: kotlin.Any){
    
        everyone("everyone"),
    
        followers("followers"),
    
        friends("friends"),
    
        self("self");
    
    }

}

