/**
* Cactacea backend API
* Cactacea / Cactacea backend API for web and mobile applications
*
* OpenAPI spec version: 18.12.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.github.cactacea.backend


import com.squareup.moshi.Json
/**
 * 
 * @param sortType Friends which sorted by accountName or friendsAt. Default is friendsAt.
 */
data class GetSessionFriendsBody (
    /* Friends which sorted by accountName or friendsAt. Default is friendsAt. */
    val sortType: GetSessionFriendsBody.SortType? = null
) {

    /**
    * Friends which sorted by accountName or friendsAt. Default is friendsAt.
    * Values: friendsAt,accountName
    */
    enum class SortType(val value: kotlin.String){
    
        @Json(name = "friendsAt") friendsAt("friendsAt"),
    
        @Json(name = "accountName") accountName("accountName");
    
    }

}

