/**
* Cactacea backend API
* Cactacea / Cactacea backend API for web and mobile applications
*
* OpenAPI spec version: 18.12.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.github.cactacea.backend

import io.github.cactacea.backend.Account
import io.github.cactacea.backend.Group

import com.squareup.moshi.Json
/**
 * 
 * @param id 
 * @param group 
 * @param account 
 * @param invitationStatus 
 * @param invitedAt 
 * @param next 
 */
data class GroupInvitation (
    val id: java.math.BigDecimal,
    val group: Group,
    val account: Account,
    val invitationStatus: GroupInvitation.InvitationStatus,
    val invitedAt: kotlin.Long,
    val next: java.math.BigDecimal? = null
) {

    /**
    * 
    * Values: noResponded,accepted,rejected
    */
    enum class InvitationStatus(val value: kotlin.String){
    
        @Json(name = "noResponded") noResponded("noResponded"),
    
        @Json(name = "accepted") accepted("accepted"),
    
        @Json(name = "rejected") rejected("rejected");
    
    }

}

