/**
* Cactacea backend API
* Cactacea / Cactacea backend API for web and mobile applications
*
* OpenAPI spec version: 18.12.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.github.cactacea.backend

import io.github.cactacea.backend.Message

import com.squareup.moshi.Json
/**
 * 
 * @param id 
 * @param name 
 * @param message 
 * @param groupPrivacyType 
 * @param invitationOnly 
 * @param authorityType 
 * @param accountCount 
 * @param lastPostedAt 
 * @param organizedAt 
 * @param next 
 */
data class Group (
    val id: java.math.BigDecimal,
    val groupPrivacyType: Group.GroupPrivacyType,
    val invitationOnly: kotlin.Boolean,
    val authorityType: Group.AuthorityType,
    val accountCount: kotlin.Long,
    val organizedAt: kotlin.Long,
    val name: kotlin.String? = null,
    val message: Message? = null,
    val lastPostedAt: java.math.BigDecimal? = null,
    val next: java.math.BigDecimal? = null
) {

    /**
    * 
    * Values: everyone,follows,followers,friends
    */
    enum class GroupPrivacyType(val value: kotlin.String){
    
        @Json(name = "everyone") everyone("everyone"),
    
        @Json(name = "follows") follows("follows"),
    
        @Json(name = "followers") followers("followers"),
    
        @Json(name = "friends") friends("friends");
    
    }

    /**
    * 
    * Values: owner,member
    */
    enum class AuthorityType(val value: kotlin.String){
    
        @Json(name = "owner") owner("owner"),
    
        @Json(name = "member") member("member");
    
    }

}

