/**
* Cactacea backend API
* Cactacea / Cactacea backend API for web and mobile applications
*
* OpenAPI spec version: 18.12.8
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.github.cactacea.backend


/**
 * 
 * @param id 
 * @param messageType 
 * @param message 
 * @param accountCount 
 * @param readAccountCount 
 * @param contentWarning 
 * @param contentDeleted 
 * @param postedAt 
 */
data class GroupMessage (
    val id: java.math.BigDecimal,
    val messageType: GroupMessage.MessageType,
    val accountCount: kotlin.Long,
    val readAccountCount: kotlin.Long,
    val contentWarning: kotlin.Boolean,
    val contentDeleted: kotlin.Boolean,
    val postedAt: kotlin.Long,
    val message: kotlin.String? = null
) {

    /**
    * 
    * Values: text,medium,stamp,groupInvitation,groupJoined,groupLeft
    */
    enum class MessageType(val value: kotlin.Any){
    
        text("text"),
    
        medium("medium"),
    
        stamp("stamp"),
    
        groupInvitation("groupInvitation"),
    
        groupJoined("groupJoined"),
    
        groupLeft("groupLeft");
    
    }

}

