/**
* Cactacea backend API
* Cactacea / Cactacea backend API for web and mobile applications
*
* OpenAPI spec version: 18.12.2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.github.cactacea.backend


/**
 * 
 * @param accountIds Account Identifies.
 */
data class PostInvitationAccountsBody (
    /* Account Identifies. */
    val accountIds: kotlin.Array<java.math.BigDecimal>? = null
) {

}

