/**
* Cactacea backend API
* Cactacea / Cactacea backend API for web and mobile applications
*
* OpenAPI spec version: 18.11.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.github.cactacea.backend


/**
 * 
 * @param id Group identifier.
 * @param message A message will be posted.
 * @param mediumId A medium will be posted.
 */
data class PostMessageBody (
    /* Group identifier. */
    val id: java.math.BigDecimal,
    /* A message will be posted. */
    val message: kotlin.String? = null,
    /* A medium will be posted. */
    val mediumId: java.math.BigDecimal? = null
) {

}

