/**
* Cactacea backend API
* Cactacea / Cactacea backend API for web and mobile applications
*
* OpenAPI spec version: 0.6.3-SNAPSHOT
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.github.cactacea.backend


/**
 * 
 * @param name Account name.
 * @param display_name Display name.
 * @param provider_id Social account type.
 * @param password Account password.
 * @param web Profile URL.
 * @param birthday Account birthday.
 * @param location Account address.
 * @param bio Account bio.
 */
data class PostSocialAccountSignUpBody (
    /* Account name. */
    val name: kotlin.String? = null,
    /* Display name. */
    val display_name: kotlin.String? = null,
    /* Social account type. */
    val provider_id: kotlin.String? = null,
    /* Account password. */
    val password: kotlin.String? = null,
    /* Profile URL. */
    val web: kotlin.String? = null,
    /* Account birthday. */
    val birthday: java.math.BigDecimal? = null,
    /* Account address. */
    val location: kotlin.String? = null,
    /* Account bio. */
    val bio: kotlin.String? = null
) {

}

