/**
* Cactacea backend API
* Cactacea / Cactacea backend API for web and mobile applications
*
* OpenAPI spec version: 18.12.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.github.cactacea.backend


import com.squareup.moshi.Json
/**
 * 
 * @param message A feed message will be posted.
 * @param mediumIds Medium identifiers of attached.
 * @param tags Tags of feed.
 * @param privacyType Feed privacy type.
 * @param contentWarning Content warning.
 * @param expiration Expiration of a feed.
 */
data class PostFeedBody (
    /* A feed message will be posted. */
    val message: kotlin.String,
    /* Feed privacy type. */
    val privacyType: PostFeedBody.PrivacyType,
    /* Content warning. */
    val contentWarning: kotlin.Boolean,
    /* Medium identifiers of attached. */
    val mediumIds: kotlin.Array<java.math.BigDecimal>? = null,
    /* Tags of feed. */
    val tags: kotlin.Array<kotlin.String>? = null,
    /* Expiration of a feed. */
    val expiration: java.math.BigDecimal? = null
) {

    /**
    * Feed privacy type.
    * Values: everyone,followers,friends,self
    */
    enum class PrivacyType(val value: kotlin.String){
    
        @Json(name = "everyone") everyone("everyone"),
    
        @Json(name = "followers") followers("followers"),
    
        @Json(name = "friends") friends("friends"),
    
        @Json(name = "self") self("self");
    
    }

}

