/**
* Cactacea backend API
* Cactacea / Cactacea backend API for web and mobile applications
*
* OpenAPI spec version: 18.11.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.github.cactacea.backend


import com.squareup.moshi.Json
/**
 * 
 * @param reportType Report type.
 * @param reportContent Description about this report.
 */
data class PostFeedReportBody (
    /* Report type. */
    val reportType: PostFeedReportBody.ReportType,
    /* Description about this report. */
    val reportContent: kotlin.String? = null
) {

    /**
    * Report type.
    * Values: none,spam,inappropriate
    */
    enum class ReportType(val value: kotlin.String){
    
        @Json(name = "none") none("none"),
    
        @Json(name = "spam") spam("spam"),
    
        @Json(name = "inappropriate") inappropriate("inappropriate");
    
    }

}

