/**
* Cactacea backend API
* Cactacea / Cactacea backend API for web and mobile applications
*
* OpenAPI spec version: 19.9.3
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.github.cactacea.backend


/**
 * 
 * @param authType Auth type.
 * @param identifier User name.
 * @param password User password.
 */
data class PostSignInBody (
    /* Auth type. */
    val authType: PostSignInBody.AuthType,
    /* User name. */
    val identifier: kotlin.String,
    /* User password. */
    val password: kotlin.String
) {

    /**
    * Auth type.
    * Values: username,email
    */
    enum class AuthType(val value: kotlin.Any){
    
        username("username"),
    
        email("email");
    
    }

}

