/**
* Cactacea backend API
* Cactacea / Cactacea backend API for web and mobile applications
*
* OpenAPI spec version: 19.3.3
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.github.cactacea.backend


/**
 * 
 * @param groupId Group identifier.
 * @param message A message will be posted.
 */
data class PostTextBody (
    /* Group identifier. */
    val groupId: java.math.BigDecimal,
    /* A message will be posted. */
    val message: kotlin.String
) {

}

