/**
* Cactacea backend API
* Cactacea / Cactacea backend API for web and mobile applications
*
* OpenAPI spec version: 18.11.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.github.cactacea.backend


/**
 * 
 * @param followerFeed 
 * @param feedComment 
 * @param groupMessage 
 * @param directMessage 
 * @param groupInvitation 
 * @param showMessage 
 */
data class PushNotificationSetting (
    val followerFeed: kotlin.Boolean,
    val feedComment: kotlin.Boolean,
    val groupMessage: kotlin.Boolean,
    val directMessage: kotlin.Boolean,
    val groupInvitation: kotlin.Boolean,
    val showMessage: kotlin.Boolean
) {

}

