/**
* Cactacea backend API
* Cactacea / Cactacea backend API for web and mobile applications
*
* OpenAPI spec version: 18.12.8
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.github.cactacea.backend


/**
 * 
 * @param followerFeed 
 * @param feedComment 
 * @param groupMessage 
 * @param directMessage 
 * @param groupInvitation 
 * @param showMessage 
 */
data class PushNotificationSetting (
    val followerFeed: kotlin.Boolean,
    val feedComment: kotlin.Boolean,
    val groupMessage: kotlin.Boolean,
    val directMessage: kotlin.Boolean,
    val groupInvitation: kotlin.Boolean,
    val showMessage: kotlin.Boolean
) {

}

