/**
* Cactacea backend API
* Cactacea / Cactacea backend API for web and mobile applications
*
* OpenAPI spec version: 0.6.3-SNAPSHOT
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.github.cactacea.backend


/**
 * 
 * @param display_name Display name that each account shown.
 */
data class PutAccountDisplayNameBody (
    /* Display name that each account shown. */
    val display_name: kotlin.String? = null
) {

}

