/**
* Cactacea backend API
* Cactacea / Cactacea backend API for web and mobile applications
*
* OpenAPI spec version: 18.11.3
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.github.cactacea.backend


/**
 * 
 * @param displayName Display name that each account shown.
 */
data class PutAccountDisplayNameBody (
    /* Display name that each account shown. */
    val displayName: kotlin.String? = null
) {

}

