/**
* Cactacea backend API
* Cactacea / Cactacea backend API for web and mobile applications
*
* OpenAPI spec version: 19.9.3
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.github.cactacea.backend


/**
 * 
 * @param displayName Display name.
 * @param web Profile URL.
 * @param birthday User birthday.
 * @param location User address.
 * @param bio User bio.
 */
data class PutSessionProfileBody (
    /* Display name. */
    val displayName: kotlin.String,
    /* Profile URL. */
    val web: kotlin.String? = null,
    /* User birthday. */
    val birthday: java.math.BigDecimal? = null,
    /* User address. */
    val location: kotlin.String? = null,
    /* User bio. */
    val bio: kotlin.String? = null
) {

}

