/**
* Cactacea backend API
* Cactacea / Cactacea backend API for web and mobile applications
*
* OpenAPI spec version: 18.12.8
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.github.cactacea.backend


/**
 * 
 * @param oldPassword Account old password.
 * @param newPassword Account new password.
 */
data class PutSessionPasswordBody (
    /* Account old password. */
    val oldPassword: kotlin.String,
    /* Account new password. */
    val newPassword: kotlin.String
) {

}

